name: Jekyll Site
markdown: redcarpet
pygments: true


#Default Configuration

safe:        true
auto:        false
server:      false
baseurl:    /
permalink: /:title.html

url: http://localhost:4000