name: Jekyll Site
markdown: redcarpet
pygments: true


#Default Configuration

safe:        true
auto:        false
server:      false
baseurl:    http://summerdaysinbloom.github.io/cbpb/
permalink: /:title.html

url: http://summerdaysinbloom.github.io/cbpb/