name: Jekyll Site
markdown: redcarpet
pygments: true


#Default Configuration

safe:        true
auto:        false
server:      false
baseurl:    http://summerdaysinbloom.github.io/cbpb/
permalink: /blog/:title.html

# baseurl: /
# permalink: /blog/:title.html

url: http://summerdaysinbloom.github.io/cbpb/
# url: http:s//localhost:4000/